server : 
    port : 80


spring :
    mvc :
        view :
            prefix : /views/
            suffix : .jsp						
    datasource :
        driver-class-name : com.mysql.cj.jdbc.Driver
        url : jdbc:mysql://localhost:3306/onop_db?characterEncoding=utf-8
        username : onop
        password : 123456

###  DB : 언더스코어 <->  java : 카멜
mybatis:
    configuration :
        map-underscore-to-camel-case : true